package com.sickkids.caliper.common;

public enum ParticipantType
{
	LECTURER,
	TEACHING_ASSISTANT,
	INTERACTIVE_VIEWER1,
	INTERACTIVE_VIEWER2,
	ONEWAY_VIEWER1,
	ONEWAY_VIEWER2,
	ONEWAY_VIEWER3,
	ONEWAY_VIEWER4,
	ONEWAY_VIEWER5,
	ONEWAY_VIEWER6,
	NONE
}
